name: Mobile Authentication Security Tests

run-name: 🔒 Mobile Auth Security Tests - ${{ github.actor }}

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Security Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [11]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
          
      - name: Set up Appium
        run: |
          npm install -g appium@next
          appium driver install uiautomator2
          appium driver install xcuitest
          
      - name: Start Appium Server
        run: |
          appium --log appium.log --relaxed-security &
          sleep 5
          echo "Appium server started"
          
      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: pixel
          script: echo "Emulator is running"
          
      - name: Run Tests
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml
        env:
          MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
          
      - name: Generate Allure Report
        if: always()
        run: mvn allure:report
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            target/surefire-reports
            target/site/allure-maven-plugin
            
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: target/screenshots
